import { Theme } from '.';

export const bpfLightTheme: Theme = {
  name: 'bpfLight',
  properties: {
    '--background': '#fafafa',
    '--on-background': '#000',
    '--select-border-color': '#cc223e',
    '--select-icon-background': 'rgba(211, 66, 90, 0.6)',
    '--select-border-light-color': '#ea8192',
    '--font-family': 'Montserrat, Helvetica, Arial, sans-serif',
    '--primary-text': '#000',
    '--on-primary': '#616c75',
    '--on-primary-muted': '#a4aaaf',
    '--a-color': '#cc223e',
    '--a-hover-color': '#9b1c32',
    '--theme-color-main': '#cc223e',
    '--theme-color-main-dark': '#9b1c32',
    '--picture-tile-background': 'rgba(0, 0, 0, 0.5)',
    '--row-header': 'capitalize',
    '--row-header-color': '#000000',
    '--sub-header-color': '#b8bdc1',
    '--radio-button-unselected': '#a4aaaf',
    '--radio-button-selected': '#ffffff',
    '--payoff-projector-arrow': '#63b1bc',
    '--pill-dark-background': '#63b1bc',
    '--pill-box-shadow': '',
    '--pill-border': '1px solid rgba(151, 151, 151, 1)',
    '--pill-padding': '7px',
    '--progress-bar-color': '#4a4a4a',
    '--black-text': '#404243',
    '--pill-dark-font-weight': 'bold',
    '--completed-icon-color': '#63b1bc',
    '--primary-border-radius': '24px',
    '--primary': '#63b1bc',
    '--link-text': '#c8102e',
    '--link-decoration': 'underline',
    '--quiz-primary': '#fff',
    '--on-quiz-primary': '#5b6770',
    '--on-quiz-secondary': '#353535'
  },
  featureFlagVariation: ['newHomepage', 'existingHomepageNewBranding'],
  iconVersion: 'v4'
};
